[menu]
  [[menu.main]]
    identifier = "posts"
    pre = ""
    post = ""
    name = "归档"
    url = "/posts/"
    title = ""
    weight = 1
    [menu.main.params]
      class = ""
      draft = false
      icon = "fa-solid fa-archive"
      type = ""
  [[menu.main]]
    identifier = "categories"
    pre = ""
    post = ""
    name = "分类"
    url = "/categories/"
    title = ""
    weight = 2
    [menu.main.params]
      icon = "fa-solid fa-th"
  [[menu.main]]
    identifier = "tags"
    pre = ""
    post = ""
    name = "标签"
    url = "/tags/"
    title = ""
    weight = 3
    [menu.main.params]
      icon = "fa-solid fa-tags"

[params]
  version = "0.2.X" 
  description = "lingllqs的分享站"
  keywords = ["Hugo", "ArchLinux", "技术", "编程", "IT", "网络", "操作系统"]
  defaultTheme = "dark"
  fingerprint = "sha256"
  dateFormat = "2006-01-02"
  images = ["/images/wallpaper/民族少女.jpg"]
  enablePWA = true
  externalIcon = true  
  enableGitInfo = true
  navigationReverse = true
  disableThemeInject = false
  [params.app]
    title = "树洞"
    noFavicon = false
    svgFavicon = ""
    iconColor = "#5bbad5"
    tileColor = "#da532c"
    [params.app.themeColor]
      light = "#f8f8f8"
      dark = "#252627"
  [params.search]
    enable = true 
    type = "lunr"
    contentLength = 4000
    placeholder = "搜索"
    maxResultLength = 10
    snippetLength = 30
    highlightTag = "em"
    absoluteURL = false
    [params.search.algolia]
      index = ""
      appID = ""
      searchKey = ""
    [params.search.fuse]
      isCaseSensitive = false
      minMatchCharLength = 2
      findAllMatches = false
      location = 0
      threshold = 0.3
      distance = 100
      ignoreLocation = false
      useExtendedSearch = false
      ignoreFieldNorm = false
  [params.header]
    desktopMode = "auto"
    mobileMode = "auto"
    [params.header.title]
      # logo = "/svg/滑稽.svg"
      logo = ""
      name = "修仙者聚集地"
      pre = ""
      post = ""
      typeit = true
    [params.header.subtitle]
      name = ""
      typeit = true
  [params.breadcrumb]
    enable = true
    sticky = false
    showHome = false
  [params.footer]
    enable = true
    custom = ""
    hugo = true
    copyright = true
    author = true
    since = ""
    wordCount = true
    gov = ""
    icp = ""
    license = ""
    [params.footer.siteTime]
      enable = false
      animate = true
      icon = "fa-solid fa-heartbeat"
      pre = ""
      value = "" 
    [params.footer.order]
      powered = 0
      copyright = 0
      statistics = 0
      visitor = 0
      beian = 0
  [params.section]
    paginate = 20
    dateFormat = "01-02"
    rss = 10
    [params.section.recentlyUpdated]
      enable = false
      rss = false
      days = 30
      maxCount = 10
  [params.list]
    paginate = 20
    dateFormat = "01-02"
    rss = 10
  [params.tagcloud]
    enable = false
    min = 14 
    max = 32 
    peakCount = 10 
    orderby = "name" 
  [params.home]
    rss = 10
    [params.home.profile]
      enable = true
      gravatarEmail = ""
      avatarURL = ""
      avatarMenu = ""
      title = "技术交流"
      subtitle = "窗前明月光\n疑似地上霜"
      typeit = true
      social = true
      disclaimer = ""
    [params.home.posts]
      enable = true
      paginate = 6
  [params.social]
    GitHub = "lingllqs"
    Linkedin = ""
    Twitter = ""
    Instagram = ""
    Facebook = ""
    Telegram = ""
    Medium = ""
    Gitlab = ""
    Youtubelegacy = ""
    Youtubecustom = ""
    Youtubechannel = ""
    Tumblr = ""
    Quora = ""
    Keybase = ""
    Pinterest = ""
    Reddit = ""
    Codepen = ""
    FreeCodeCamp = ""
    Bitbucket = ""
    Stackoverflow = ""
    Weibo = ""
    Odnoklassniki = ""
    VK = ""
    Flickr = ""
    Xing = ""
    Snapchat = ""
    Soundcloud = ""
    Spotify = ""
    Bandcamp = ""
    Paypal = ""
    Fivehundredpx = ""
    Mix = ""
    Goodreads = ""
    Lastfm = ""
    Foursquare = ""
    Hackernews = ""
    Kickstarter = ""
    Patreon = ""
    Steam = ""
    Twitch = ""
    Strava = ""
    Skype = ""
    Whatsapp = ""
    Zhihu = ""
    Douban = ""
    Angellist = ""
    Slidershare = ""
    Jsfiddle = ""
    Deviantart = ""
    Behance = ""
    Dribbble = ""
    Wordpress = ""
    Vine = ""
    Googlescholar = ""
    Researchgate = ""
    Mastodon = ""
    Thingiverse = ""
    Devto = ""
    Gitea = ""
    XMPP = ""
    Matrix = ""
    Bilibili = ""
    ORCID = ""
    Liberapay = ""
    Ko-Fi = ""
    BuyMeaCoffee = ""
    Linktree = ""
    QQ = ""
    QQGroup = "" 
    Diaspora = ""
    CSDN = ""
    Discord = ""
    DiscordInvite = ""
    Lichess = ""
    Pleroma = ""
    Kaggle = ""
    MediaWiki= ""
    Plume = ""
    HackTheBox = ""
    RootMe = ""
    Feishu = ""
    TryHackMe = ""
    Douyin = ""
    TikTok = ""
    Phone = ""
    Email = ""
    RSS = true
  [params.page]
    authorAvatar = true
    hiddenFromHomePage = false
    hiddenFromSearch = false
    twemoji = false
    lightgallery = false
    ruby = true
    fraction = true
    fontawesome = true
    license = '<a rel="license external nofollow noopener noreferrer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'
    linkToMarkdown = true
    rssFullText = false
    pageStyle = "narrow"
    autoBookmark = true
    wordCount = true
    readingTime = true
    endFlag = ""
    instantPage = false
    collectionList = true
    collectionNavigation = false
    [params.page.repost]
      enable = false
      url = ""
    [params.page.toc]
      enable = true
      keepStatic = false
      auto = true
      position = "right"
    [params.page.expirationReminder]
      enable = false
      reminder = 90
      warning = 180
      closeComment = false
    [params.page.math]
      enable = true
      inlineLeftDelimiter = ""
      inlineRightDelimiter = ""
      blockLeftDelimiter = ""
      blockRightDelimiter = ""
      copyTex = true
      mhchem = true
    [params.page.code]
      copy = true
      edit = true
      maxShownLines = 10
    [params.page.mapbox]
      accessToken = ""
      lightStyle = "mapbox://styles/mapbox/light-v9"
      darkStyle = "mapbox://styles/mapbox/dark-v9"
      navigation = true
      geolocate = true
      scale = true
      fullscreen = true
    [params.page.reward]
      enable = false
      animation = false
      position = "after"
      mode = "static"
      [params.page.reward.ways]
    [params.page.share]
      enable = true
      Twitter = false
      Facebook = false
      Linkedin = false
      Whatsapp = false
      Pinterest = false
      Tumblr = false
      HackerNews = false
      Reddit = false
      VK = false
      Buffer = false
      Xing = false
      Line = false
      Instapaper = false
      Pocket = false
      Flipboard = false
      Weibo = true
      Myspace = false
      Blogger = false
      Baidu = true
      Odnoklassniki = false
      Evernote = false
      Skype = false
      Trello = false
      Mix = false
    [params.page.comment]
      enable = true
      [params.page.comment.artalk]
        enable = false
        server = "https://yourdomain"
        site = "默认站点"
        placeholder = ""
        noComment = ""
        sendBtn = ""
        editorTravel = true
        flatMode = "auto"
        lightgallery = false
        locale = "" 
        emoticons = ""
        nestMax = 2
        nestSort = "DATE_ASC" 
        vote = true
        voteDown = false
        uaBadge = true
        listSort = true
        imgUpload = true
        preview = true
        versionCheck = true
      [params.page.comment.disqus]
        enable = false
        shortname = ""
      [params.page.comment.gitalk]
        enable = false
        owner = ""
        repo = ""
        clientId = ""
        clientSecret = ""
      [params.page.comment.valine]
        enable = true
        appId = "ZtaCuooNxUcOqZ44oEeRZvpa-gzGzoHsz"
        appKey = "ZQm92JiXmMQqpk6hi7Zqoi0w"
        placeholder = ""
        avatar = "mp"
        meta = ""
        requiredFields = ""
        pageSize = 10
        lang = ""
        visitor = true
        recordIP = true
        highlight = true
        enableQQ = false
        serverURLs = ""
        emoji = ""
        commentCount = true 
      [params.page.comment.waline]
        enable = false
        serverURL = ""
        pageview = false 
        emoji = ["//unpkg.com/@waline/emojis@1.1.0/weibo"]
        meta = ["nick", "mail", "link"]
        requiredMeta = []
        login = "enable"
        wordLimit = 0
        pageSize = 10
        imageUploader = false 
        highlighter = false 
        comment = false 
        texRenderer = false 
        search = false 
        recaptchaV3Key = "" 
        reaction = false 
      [params.page.comment.facebook]
        enable = false
        width = "100%"
        numPosts = 10
        appId = ""
        languageCode = ""
      [params.page.comment.telegram]
        enable = false
        siteID = ""
        limit = 5
        height = ""
        color = ""
        colorful = true
        dislikes = false
        outlined = false
      [params.page.comment.commento]
        enable = false
      [params.page.comment.utterances]
        enable = false
        repo = ""
        issueTerm = "pathname"
        label = ""
        lightTheme = "github-light"
        darkTheme = "github-dark"
      [params.page.comment.twikoo]
        enable = false
        envId = ""
        region = ""
        path = ""
        visitor = true
        commentCount = true
        lightgallery = false
        katex = false
      [params.page.comment.giscus]
        enable = false
        repo = ""
        repoId = ""
        category = ""
        categoryId = ""
        mapping = ""
        strict = "0" 
        term = ""
        reactionsEnabled = "1"
        emitMetadata = "0"
        inputPosition = "bottom" 
        lightTheme = "light"
        darkTheme = "dark"
        lazyLoad = true
    [params.page.library]
      [params.page.library.css]
      [params.page.library.js]
        flyfish = "/js/flyfish.js"
    [params.page.seo]
      images = []
      [params.page.seo.publisher]
        name = ""
        logoUrl = ""
  [params.typeit]
    speed = 100
    cursorSpeed = 1000
    cursorChar = "|"
    duration = -1
    loop = false
  [params.mermaid]
    themes = ["default", "dark"]
  [params.pangu]
    enable = true
    selector = "article" 
  [params.watermark]
    enable = false
    content = ""
    opacity = 0.1
    appendTo = ".wrapper>main"
    width = 150
    height = 20
    rowSpacing = 60
    colSpacing = 30
    rotate = 15
    fontSize = 0.85
    fontFamily = "inherit"
  [params.Busuanzi]
    enable = false
    enablePost = false
  [params.verification]
    google = ""
    bing = ""
    yandex = ""
    pinterest = ""
    baidu = ""
    so = ""
    sogou = ""
  [params.seo]
    image = ""
    thumbnailUrl = ""
  [params.analytics]
    enable = false
    [params.analytics.google]
      id = ""
      anonymizeIP = true
    [params.analytics.fathom]
      id = ""
      server = ""
  [params.cookieconsent]
    enable = true
    [params.cookieconsent.content]
      message = ""
      dismiss = ""
      link = ""
  [params.cdn]
    data = ""
  [params.compatibility]
    polyfill = false
    objectFit = false
  [params.githubCorner]
    enable = false
    permalink = "https://github.com/hugo-fixit/FixIt"
    title = "View source on GitHub"
    position = "right" 
  [params.gravatar]
    enable = false
    host = "www.gravatar.com" 
    style = "" 
  [params.backToTop]
    enable = true
    scrollpercent = false
  [params.readingProgress]
    enable = true
    start = "left"
    position = "top"
    reversed = false
    light = ""
    dark = ""
    height = "2px"
  
  [params.pace]
    enable = true
    color = "orange"
    theme = "minimal"
  [params.author]
    name = "lingllqs"
    email = "lingllqs@163.com"
    link = "https://github.com/lingllqs/lingllqs"

  [params.gitInfo]
    repo = "https://github.com/lingllqs/lingllqs"
    branch = "main"
    dir = "content"
    issueTpl = "title=[BUG]%20{title}&body=|Field|Value|%0A|-|-|%0A|Title|{title}|%0A|URL|{URL}|%0A|Filename|{sourceURL}|"
  
  [params.customFilePath]
  [params.dev]
    enable = false
    c4u = false
    githubToken = ""
    [params.dev.mDevtools]
      enable = false
      type = "vConsole"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.109.0"
